// Flyweight pattern in Go: uses a sync.Map-based pool to share BigChar instances.
// ASCII art digit data is embedded directly as string constants.
package main

import (
	"fmt"
	"os"
	"sync"
)

// bigFonts holds the ASCII art for digits 0-9 and '-'.
var bigFonts = map[rune]string{
	'0': `....######......
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
....######......
................
`,
	'1': `......##........
..######........
......##........
......##........
......##........
......##........
..##########....
................
`,
	'2': `....######......
..##......##....
..........##....
......####......
....##..........
..##............
..##########....
................
`,
	'3': `....######......
..##......##....
..........##....
......####......
..........##....
..##......##....
....######......
................
`,
	'4': `........##......
......####......
....##..##......
..##....##......
..##########....
........##......
......######....
................
`,
	'5': `..##########....
..##............
..##............
..########......
..........##....
..##......##....
....######......
................
`,
	'6': `....######......
..##......##....
..##............
..########......
..##......##....
..##......##....
....######......
................
`,
	'7': `..##########....
..##......##....
..........##....
........##......
......##........
......##........
......##........
................
`,
	'8': `....######......
..##......##....
..##......##....
....######......
..##......##....
..##......##....
....######......
................
`,
	'9': `....######......
..##......##....
..##......##....
....########....
..........##....
..##......##....
....######......
................
`,
	'-': `................
................
................
................
..##########....
................
................
................
`,
}

// BigChar holds the font data for a single character.
type BigChar struct {
	fontdata string
}

// bigCharPool is a concurrent-safe cache of BigChar instances (the flyweight pool).
var bigCharPool sync.Map

// getBigChar returns a shared BigChar for the given rune.
func getBigChar(c rune) *BigChar {
	if v, ok := bigCharPool.Load(c); ok {
		return v.(*BigChar)
	}
	data, ok := bigFonts[c]
	if !ok {
		data = string(c) + "?\n"
	}
	bc := &BigChar{fontdata: data}
	actual, _ := bigCharPool.LoadOrStore(c, bc)
	return actual.(*BigChar)
}

// BigString is a sequence of BigChar flyweight references.
type BigString struct {
	chars []*BigChar
}

// NewBigString builds a BigString from a digit string, reusing shared BigChar instances.
func NewBigString(s string) *BigString {
	bs := &BigString{chars: make([]*BigChar, 0, len(s))}
	for _, c := range s {
		bs.chars = append(bs.chars, getBigChar(c))
	}
	return bs
}

// Print outputs all the big characters.
func (bs *BigString) Print() {
	for _, bc := range bs.chars {
		fmt.Print(bc.fontdata)
	}
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: go run main.go <digits>")
		fmt.Println("Example: go run main.go 1212123")
		return
	}

	bs := NewBigString(os.Args[1])
	bs.Print()
}
